### PR TITLE
LPS-89352 Add View History to Web Content Display actions

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by balazssk** [comment]
Hi @dacousalr ,

Thank you for the quick help, I've got a 2 questions:
There are 3 "panels" of the pop up if I want to compare versions:
1 - The initial View History panel
2 - The select which version you want to compare to
3 - The comparison

The 2nd panel works just like if you've used it on the Journal Portlet, simple popup, once closed the initial 1st panel pop up remains.
The 3rd panel work a bit differently. If you call it from the Journal Portlet, the 2nd panel pop up will open this in full view mode, with a back navigation option to the Journal Portlet. If opened from the Journal Content Portlet, this will close the 2nd panel's pop up and override the 1st panel's pop up's url. The problem with this is that there is no "easy" way to navigate back to the 1st panel. (No navigation icon, and clicking the close button closes the whole pop up).

What do you think about this?

I also noticed that the 2 out of 3 other Icons' id's are suffixed with -"Icon", but maybe I just wanted to see a pattern.

Thanks!

**Comment by dacousalr** [comment]
Hi @balazssk,

I am addressing those points. However, some changes made in Master regarding if these actions should be opened in a popup or not for that version might make me reconsider this approach.

I will to talk to the team on Monday and I will update you.

Thank you for your patience

**Comment by balazssk** [comment]
Hi @dacousalr ,
Can you please share any news from the Monday meeting?

**Comment by dacousalr** [comment]
Hi @balazssk,

Sorry for the delay in my response.

This fix continues in pavel-savinov#327

**Pull request closed without merging**
